### ISSUE TITLE
As a guest, I can play a new game

### ISSUE THREAD

**Issue by johncambefort** [johncambefort/kxstorygame#1]
## Tasks:

Front:
- [ ] #2
- [ ] #3
- [ ] #5

Back:
- [x] https://github.com/johncambefort/kxstorygame-back/issues/2
- [ ] https://github.com/johncambefort/kxstorygame-back/issues/7
- [ ] https://github.com/johncambefort/kxstorygame-back/issues/4

Dev tasks:
- [ ] Add rake task to seed db
